[build]
command = "echo 'Build command goes here'"
functions = "netlify/functions"
publish = "/"
[functions]
included_files = ["ext/**"]
[functions. "*"]
node_bundler = "esbuild"
node_target = "es2022"
